name: "Fixed Workflow"
on:
  issues:
    types: [opened]

jobs:
  handle_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Print issue body
      run: echo ${{ github.event.issue.body }} > issues.txt
      env:
        MY_API_KEY: secrets.MY_API_KEY
      shell: bash
